ci:
  # pre-commit.ci will open PRs updating our hooks once a month
  autoupdate_schedule: monthly

repos:
  # autoformat and lint Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: c59bba8fb259db0fec2bbb77ad8ba51ea7341b56  # frozen: v0.15.20
    hooks:
      - id: ruff
        types_or:
          - python
          - jupyter
        args: [--fix, --show-fixes]
      - id: ruff-format
        types_or:
          - python
          - jupyter

  # strip output because notebook outputs are not shareable
  - repo: https://github.com/kynan/nbstripout
    rev: 34071b78c181af3bf5af955c1426466e096fc3db  # frozen: 0.9.1
    hooks:
      - id: nbstripout

  # Autoformat: yaml
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
    hooks:
      - id: pretty-format-yaml
        args: [--autofix, --offset, '2']

  # Autoformat: markdown
  - repo: https://github.com/executablebooks/mdformat
    rev: 82912cdaea4fb830f751504486a7879c70526547  # frozen: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-myst
          - mdformat-black

  # github actions security checks
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: e3eebf65325ccc992422292cb7a4baee967cf815 # frozen: v1.26.1
    hooks:
      - id: zizmor
        args:
          - --fix

  # Autoformat and linting, misc. details
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
