name: tests

on:
  pull_request:
    paths-ignore:
      - docs/**
      - .github/workflows/*.yaml
      - '!.github/workflows/test.yaml'
  push:
    paths-ignore:
      - docs/**
      - .github/workflows/*.yaml
      - '!.github/workflows/test.yaml'
    branches-ignore:
      - dependabot/**
      - pre-commit-ci-update-config

env:
  PYTEST_ADDOPTS: --verbose --color=yes

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      # Keep running even if one variation of the job fail
      fail-fast: false
      matrix:
        python:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install Python dependencies
        run: |
          pip install ".[test]"
          pip list

      - name: Run tests
        run: |
          python3 -m pytest --cov=jupyterhealth_client tests

      - name: upload coverage
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
